# -*- coding: utf-8 -*-
"""Orientation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jT6Wu9k7OGamgqbHSC8HbgN8H6DuPbWo
"""

A=2
B=3
C=2+3
print(C)

"""Example of Addition

Example of String
"""

Greetings="Advice na, pror"
print(Greetings)