# -*- coding: utf-8 -*-
"""Weekend_assignment_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oZ9_bTOtm1p6iWVYT2zOTkj-BaQ2FiSs
"""

# Name: Thomas S.Morris - May 25, 2026
#Problem 1
Liberia = 1847
print(Liberia)
print("Liberia")

# Problem 2
country = "Liberia"

print(country)
print(country, "became independent in", 1847)

# Problem 3
print('The year is "1847"')

# Problem 4
market_name = "Gobachop Market"   # string
total_market_table = 150           # whole number
price_per_bag = 3200.50           #decimal number
is_market_open = True             #true/false

print("Market name:", market_name)
print("Total market tables:", total_mrket_table)
print("Price per bag:", price_per_bag)
print("Is market open:", is_market_open)

print("Type of market_name:", type(market_name))
print("Type of total_market_table:", type(total_market_table))
print("Type of price:", type(price_per_bag))
print("Is market open:", type(is_market_open))

# Problem 5
current_price = 2550.75
quantity = 10

total_cost= current_price * quantity
print("Total cost for 10 bags :", total_cost, "LRD")

# Problem 6
has_scarcity = False
is_rainy = True

print("Scarcity today:", has_scarcity)
print("Rainy today:", is_rainy)

# Problem 7
price_per_bag_cassava = 800
quantity_cassava = 25

total_revenue = price_per_bag_cassava * quantity_cassava
print("Total revenue for cassava sales:", total_revenue, "LRD")

# Problem 8
today_price = 3200
increase = 150
tomorrow_price = today_price + increase
print("Tomorrow's rice price:", tomorrow_price, "LRD")

# Problem 9
total_onion_cost =1800
numbers_of_traders = 3

cost_per_trader = total_onion_cost / numbers_of_traders
print("Cost per trader for the shared bag of onions:", cost_per_trader, "LRD")

# Problem 10
original_price = 2500
discount_rate = 0.10  # 10% written as a decimal
discount_amount = original_price * discount_rate
final_price = original_price - discount_amount

print("Discount amount subtracted:", discount_amount, "LRD")
print("Final price for palm oil after discount:", final_price, "LRD")

# Problem 11
item = "cassava"
price = 800

print(item)     # Prints the value: cassava
print("item")   # Prints th word: item
print(price)    # prints the value: 800
print("price")  # Prints the word: price

# Problem 12
product = "pepper"

cost = 150.50
print("One bag of", product, "costs", cost, "LRD")

# Bonus Problem
Liberia = 1847

print("Liberis became independent in", Liberia)
print('"Liberia is', Liberia, 'years old?"')